version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: pensieve_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - pensieve_data:/data/db

volumes:
  pensieve_data:

